<script>src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
<script>
setInterval(function(){
$.ajax({
    url:"fetch_trame.php",
    method:"POST",
    /*
    success:function(data){
        $('.result').html(data);
    }
    */
  });
},3000);
</script>